export const popularPosts = [
  {
    id: 101,
    title: '퇴근길에 포포랑 같이 왔어요',
    content: '포포 덕분에 월요일도 버틸 수 있었어요.',
    image: '/images/community/community01.png',
    author: '하찮은회사원',
    date: '2시간 전',
    likes: '1,200',
    comments: 128,
  },
  {
    id: 102,
    title: '뭉치 키링 실물 후기',
    content: '가방에 달았더니 너무 귀여워요.',
    image: '/images/community/community02.png',
    author: '익명',
    date: '5시간 전',
    likes: 842,
    comments: 62,
  },
  {
    id: 103,
    title: '야근하는 나, 야근당하는 반디!',
    content: '오늘도 반디 덕분에 잘 버텼어요.',
    image: '/images/community/community03.png',
    author: '직공후직장',
    date: '1일 전',
    likes: 730,
    comments: 48,
  },
]

export const communityPosts = [
  {
    id: 1,
    title: '새로 산 스티커로 노트 꾸미기 ✨',
    image: '/images/community/community04.png',
    author: '디자인하는하찮이',
    date: '1시간 전',
    createdAt: '2026-09-23T11:00:00',
    likes: 56,
    comments: 7,
    category: '굿즈 활용법',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 2,
    title: '카페에서도 함께 ☕',
    image: '/images/community/community05.png',
    author: '커피와하찮이',
    date: '3시간 전',
    createdAt: '2026-09-23T09:00:00',
    likes: 120,
    comments: 18,
    category: '친구의 하루',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 3,
    title: '오늘도 하늘이 예쁘다.',
    image: '/images/community/community06.png',
    author: '익명',
    date: '5시간 전',
    createdAt: '2026-09-23T07:00:00',
    likes: 42,
    comments: 3,
    category: '하찮은 이야기',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 4,
    title: '일하기 싫은데 ... 기운이 보면서 버텨요.',
    image: '/images/community/community07.png',
    author: '하찮은직장인',
    date: '7시간 전',
    createdAt: '2026-09-23T05:00:00',
    likes: 98,
    comments: 12,
    category: '직장인 공감',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 5,
    title: '기운이랑 한복 데이트 🩶',
    image: '/images/community/community08.png',
    author: '최애가기운이인사람',
    date: '1일 전',
    createdAt: '2026-09-22T11:00:00',
    likes: 76,
    comments: 9,
    category: '친구 자랑',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 6,
    title: '포포랑 짝이랑 함께한 산책 🌳',
    image: '/images/community/community09.png',
    author: '하찮은회사원',
    date: '1일 전',
    createdAt: '2026-09-22T09:00:00',
    likes: 64,
    comments: 8,
    category: '친구의 하루',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 7,
    title: '짝이 충전기 덕분에 책상 위가 더 깔끔해졌어요 ✨',
    image: '/images/community/community10.png',
    author: '디자인하는하찮이',
    date: '2일 전',
    createdAt: '2026-09-21T11:00:00',
    likes: 88,
    comments: 11,
    category: '굿즈 활용법',
    tags: ['포포', '굿즈꾸미기'],
  },
  {
    id: 8,
    title: '반디 하나 두니까 든든해요',
    image: '/images/community/community11.png',
    author: '반디좋아',
    date: '2일 전',
    createdAt: '2026-09-21T09:00:00',
    likes: 51,
    comments: 5,
    category: '친구 자랑',
    tags: ['포포', '굿즈꾸미기'],
  },
]

export const communityCategories = [
  '전체',
  '친구 자랑',
  '친구의 하루',
  '하찮은 이야기',
  '굿즈 활용법',
  '직장인 공감',
  '자유 수다',
]